# Generated by Django 6.1.1 on 2026-09-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_lunarmonth_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunarevent',
            name='event_type',
            field=models.CharField(choices=[('lunar_day', 'Lunar Day'), ('full_moon', 'Full Moon'), ('new_moon', 'New Moon')], default='lunar_day', max_length=20),
        ),
        migrations.AlterField(
            model_name='lunarevent',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
