# Generated by Django 6.1.1 on 2026-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_lunarevent_event_type_alter_lunarevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunarevent',
            name='month_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='lunarevent',
            name='month_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
